services:
  - type: web
    name: mafia-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 mafia_roles.py"
    build:
      environment:
        PYTHON_VERSION: 3.11
